default: &default
  adapter: 'sqlite3'
  database: 'db/development.sqlite'

development:
  <<: *default

test:
  <<: *default
  database: 'db/test.sqlite'

create_user:
  <<: *default
  database: 'create_user'